name: Build and Publish Containers
on:
  workflow_call:
  push:
    branches:
      - master
jobs:
  build-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build containers
        run: |
          docker build . --tag topo-imagery-test --label "github_run_id=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - if: github.ref == 'refs/heads/master' && contains(github.event.head_commit.message, 'release:')
        name: Publish Containers for Release
        run: ./.github/scripts/publish_containers.sh true
        shell: bash

      - if: ${{!(github.ref == 'refs/heads/master' && startsWith(github.event.head_commit.message, 'release:'))}}
        name: Publish Containers
        run: |
          echo "${{ github.ref }}"
          echo "${{ github.event.head_commit.message }}"
          ./.github/scripts/publish_containers.sh false
        shell: bash
