on:
  push:
    branches:
      - master

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: python
          token: ${{ secrets.GITHUB_TOKEN }}
          pull-request-title-pattern: "release: ${version}"

  publish-release:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Build containers
        run: |
          docker build -f Dockerfile.imagery . --tag topo-imagery --label "github_run_id=${GITHUB_RUN_ID}"
          docker build -f Dockerfile.elevation . --tag topo-elevation --label "github_run_id=${GITHUB_RUN_ID}"

      - name: Log in to registry
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

      - name: Publish Containers
        run: |
          GIT_VERSION=$(git describe --tags --always --match 'v*')
          GIT_VERSION_MAJOR=$(echo $GIT_VERSION | cut -d. -f1)
          GIT_VERSION_MAJOR_MINOR=$(echo $GIT_VERSION | cut -d. -f1,2)

          docker tag topo-imagery ghcr.io/paulfouquet/topo-imagery:latest
          docker tag topo-imagery ghcr.io/paulfouquet/topo-imagery:${GIT_VERSION_MAJOR}
          docker tag topo-imagery ghcr.io/paulfouquet/topo-imagery:${GIT_VERSION_MAJOR_MINOR}
          docker tag topo-imagery ghcr.io/paulfouquet/topo-imagery:${GIT_VERSION}

          docker push --all-tags ghcr.io/paulfouquet/topo-imagery

          docker tag topo-elevation ghcr.io/paulfouquet/topo-elevation:latest
          docker tag topo-elevation ghcr.io/paulfouquet/topo-elevation:${GIT_VERSION_MAJOR}
          docker tag topo-elevation ghcr.io/paulfouquet/topo-elevation:${GIT_VERSION_MAJOR_MINOR}
          docker tag topo-elevation ghcr.io/paulfouquet/topo-elevation:${GIT_VERSION}

          docker push --all-tags ghcr.io/paulfouquet/topo-elevation
